# In this notebook, we're going to cover most fundamental concepts of tensors using Tensorflow

More specifically we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your regular python functioning).
* Using GPU with TensorFlow or TPU.
* Exercises.

# Introdution to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# creating tensors with tf.constant

scalar = tf.constant(21)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [ ]:
# check the dimensions
scalar.ndim

0

In [ ]:
# let's create a vector
vector = tf.constant([21,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([21, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# let's create a matrix

matrix = tf.constant([[1,2],
                      [2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# let's create a tensor

tensor = tf.constant([[[1,2,3],[1,2,3]],
                      [[3,4,5],[4,5,6]],
                      [[3,4,5],[3,34,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 1,  2,  3]],

       [[ 3,  4,  5],
        [ 4,  5,  6]],

       [[ 3,  4,  5],
        [ 3, 34,  3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# let's create another tensor

tensor_2 = tf.constant([[[[1,2,3,4],[3,343,343,43]],[[34,34,34,34],[45,3,4542,435]]]
                        ,[[[343,343,454,3453],[3534,345,345,345]],[[345,345,345,354],[345,345,345,35]]],
                        [[[45,345,345,345],[345,353,345,345]],[[345,345,345,345],[345345,453,534,3445]]]
                        ])
tensor_2

<tf.Tensor: shape=(3, 2, 2, 4), dtype=int32, numpy=
array([[[[     1,      2,      3,      4],
         [     3,    343,    343,     43]],

        [[    34,     34,     34,     34],
         [    45,      3,   4542,    435]]],


       [[[   343,    343,    454,   3453],
         [  3534,    345,    345,    345]],

        [[   345,    345,    345,    354],
         [   345,    345,    345,     35]]],


       [[[    45,    345,    345,    345],
         [   345,    353,    345,    345]],

        [[   345,    345,    345,    345],
         [345345,    453,    534,   3445]]]], dtype=int32)>

In [ ]:
tensor_2.ndim

4

##  creating  tensors with `tf.Variable`.

In [ ]:
changeable_tensor = tf.Variable([1,3])
unchange_tensor = tf.constant([1,3])
changeable_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
changeable_tensor[0] = 3

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(3)
changeable_tensor

In [ ]:
unchange_tensor[0] = 4

In [ ]:
unchange_tensor[0].assign(3)

In [ ]:
v = tf.Variable(1., shape=tf.TensorShape(None))
v.assign([[1.]])


In [ ]:
from random import random
### creating random tensors

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(4,3,4))
random_1

In [ ]:
random_1.ndim

In [ ]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [ ]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

In [ ]:
bool_variable.dtype

In [ ]:
complex_variable.dtype

In [ ]:
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.math.argmax(my_variable))

# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, [1,4]))

In [ ]:
tf.reshape(my_tensor , shape=(1,4) )

In [ ]:
my_tensor

In [ ]:
my_variable

In [ ]:
a = tf.Variable([2.0, 3.0])
# This will keep the same dtype, float32
a.assign([1, 2])
# Not allowed as it resizes the variable:
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

In [ ]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]

In [ ]:
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor + 1, name="Mark")

# These are elementwise-unequal, despite having the same name
print(a == b)

In [ ]:
a

In [ ]:
b

In [ ]:
b+1

In [ ]:
# tf.random.set_seed(42)
not_shuffled = tf.constant([[3,4,4],
                            [4,45,5],
                            [45,92,99]])

tf.random.shuffle(not_shuffled,seed=44)

In [ ]:
tf.expand_dims(not_shuffled,axis=0)

In [ ]:
new = not_shuffled[ ..., tf.newaxis]

In [ ]:
new

In [ ]:
%time
tensor * tensor

In [ ]:
%time
tf.linalg.matmul(tensor,tensor)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.39 µs


InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2,3], In[1]: [3,2,3] [Op:BatchMatMulV2] name: 

In [ ]:
tensor =tf.constant([[1,2,3],
                     [4,5,6],
                    [7,8,9]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
%time
tensor * tensor

CPU times: user 14 µs, sys: 2 µs, total: 16 µs
Wall time: 19.8 µs


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [ ]:
%time
tensor @ tensor

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 8.34 µs


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [ ]:
%time
tf.matmul(tensor , tensor)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.63 µs


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

## Changing Tensor datatypes

In [ ]:
a= tf.constant([1,3])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [ ]:
b = tf.cast(a,dtype=tf.float32)
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 3.], dtype=float32)>

In [ ]:
c=tf.cast(b,dtype=tf.float16)
c

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 3.], dtype=float16)>

In [ ]:
import numpy as np
d = tf.constant(np.random.randint(0,100,size=50))
d

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([26, 61, 75, 60, 45, 86,  8, 35, 36, 91, 89, 54, 95, 45, 21, 83, 24,
       58, 64, 25, 79, 19, 79, 67, 87,  6, 89, 93, 10, 46, 19, 72, 62, 36,
       15, 14, 88, 81, 96, 12, 88, 45, 65, 87, 93,  8, 57, 47, 69, 78])>

## Aggregation operators

In [ ]:
# minimum in tensor
tf.reduce_min(d) , np.min(d)

(<tf.Tensor: shape=(), dtype=int64, numpy=6>, 6)

In [ ]:
# maximum in tensor

tf.reduce_max(d) , np.max(d)

(<tf.Tensor: shape=(), dtype=int64, numpy=96>, 96)

In [ ]:
# mean of tensor

tf.reduce_mean(d)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
# sum of tensor

tf.reduce_sum(d)


<tf.Tensor: shape=(), dtype=int64, numpy=2788>

In [ ]:
# variance of tensor
d= tf.constant([[3,4],
                [2,4]], dtype=tf.float32)
tf.math.reduce_variance(d)

<tf.Tensor: shape=(), dtype=float32, numpy=0.6875>

In [ ]:
# finding  standard deviation
tf.math.reduce_std(d)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8291562>

In [ ]:
np.sqrt(tf.math.reduce_variance(d))

0.8291562

## one hot Encoding

In [ ]:
# let's create a custom list
random_list = [0,1,3,4] # these values represents indices of red , green , black , purple colors

tf.one_hot(random_list , depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [37]:
# custom adding on_value and  off_value

tf.one_hot(random_list,depth=5, on_value="yes", off_value="no")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no', b'no'],
       [b'no', b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'no', b'yes']], dtype=object)>

In [41]:
print(tf.one_hot(random_list , depth=6 , axis=0))
# axis = 0 means rows will be taken by depth if 1 viceversa

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]], shape=(6, 4), dtype=float32)


In [43]:
# for filling ones and zeros we have

tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [44]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [45]:
# for custom filling of data in specific shape we have tf.fill
tf.fill([3,4],10)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

In [54]:
# for creating indentity matrices

tf.eye(4 #no.of rows
       ,
       5
       #no.of columns
       )

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

### MATH operations

In [55]:
# let's create a square of a tensor

t=np.arange(1,10)

tf.square(t)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [57]:
#   square root of t , since we have the dtype is int32 , but sqrt may have to
# produce float values tensorflow always try to produce the ouput in the dtype of input so we need to change dtype of input

tf.sqrt(tf.cast(t,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [59]:
# Similar to sqrt , log also produces the dtype in float , so we have to change the dtype of input

tf.math.log(tf.cast(t,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [63]:
tf.math.log(10.0)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3025851>

In [73]:
tf.math.rint(2.5) # rounding the number to closest integer

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [74]:
random = np.random.randint(1,39,10)
random

array([22, 24, 37,  4, 28, 23, 16, 28, 30,  2])

In [76]:
tf.math.top_k(random,k=4)

TopKV2(values=<tf.Tensor: shape=(4,), dtype=int64, numpy=array([37, 30, 28, 28])>, indices=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 8, 4, 7], dtype=int32)>)

### NUMPY and TENSORS

In [80]:
# converting numpy array into tensors

j = tf.constant(np.array([1,3,5]))
j,type(j)

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 3, 5])>,
 tensorflow.python.framework.ops.EagerTensor)

In [81]:
# converting tensor into numpy

np.array(j), type(np.array(j))

(array([1, 3, 5]), numpy.ndarray)

In [82]:
# OR
j.numpy() , type(j.numpy())

(array([1, 3, 5]), numpy.ndarray)

In [83]:
# there is a slight diffence between tensor dtype and numpy dtype

numpy_arr = tf.constant(np.array([1,2,3]))
tensor_arr = tf.constant([1,2,3])

numpy_arr.dtype, tensor_arr.dtype

(tf.int64, tf.int32)

In [94]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [93]:
!nvidia


/bin/bash: line 1: nvidia: command not found
